name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Build
        run: npm run build

      - name: Show built index.html (first 40 lines)
        run: |
          echo "===== dist/index.html (head) =====" 
          sed -n '1,40p' dist/index.html || true

      - name: Upload dist as artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          clean: true
